[server]
# Enable CORS for production deployment
enableCORS = true
# Enable XSRF protection for security
enableXsrfProtection = true
# Set the base path for imports
scriptPath = "."
# Increase timeout for long-running operations
connectionTimeout = 300
# Port to run on (will use default 8501 if not specified)
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#0466c8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[runner]
# This helps with Python module imports
moduleImportPath = "."

[pythonPath]
# Add the project root to the Python path
path = "."

[server.headless]
# Headless mode for deployment
headless = true

[cache]
# Cache settings for better performance
enabled = true

