# .streamlit/secrets.toml
[default]
# Default environment for local development

[openai]
api_key = ""  # This will be set via Streamlit Cloud secrets manager
base_url = "https://api.aivercelabs.com/v1"  # Default AI Verde URL
