# .streamlit/secrets.toml
# This file contains secrets for local development
# For deployment to Streamlit Cloud, add these secrets in the Streamlit Cloud dashboard
# https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management
# IMPORTANT: NEVER commit this file with actual secrets to your repository

[default]
# Default environment for local development

[openai]
# OpenAI API configuration
# These should be set in the Streamlit Cloud dashboard
OPENAI_API_KEY  = ""
OPENAI_BASE_URL = "https://llm-api.cyverse.ai"
OPENAI_MODEL = "gpt-4"  # Specify which model to use

[database]
# Add database connection strings here if needed
# connection_string = ""  # Set this via Streamlit Cloud secrets manager

[app]
# Application-specific settings
environment = "production"  # Options: development, staging, production
